"""First

Revision ID: 1b1165cca9d2
Revises: 
Create Date: 2022-06-09 17:33:55.562435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1165cca9d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('occupation')
    op.drop_table('human')
    op.drop_table('lord')
    op.drop_table('child')
    op.drop_table('villager')
    op.drop_table('villager_occupation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('villager_occupation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('villager_id', sa.INTEGER(), nullable=False),
    sa.Column('villager_profession', sa.VARCHAR(), nullable=True),
    sa.Column('experience', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['villager_id'], ['villager.villager_id'], ),
    sa.ForeignKeyConstraint(['villager_profession'], ['occupation.profession'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('villager',
    sa.Column('villager_id', sa.INTEGER(), nullable=False),
    sa.Column('church_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['human.church_id'], ),
    sa.PrimaryKeyConstraint('villager_id'),
    sa.UniqueConstraint('villager_id')
    )
    op.create_table('child',
    sa.Column('church_id', sa.INTEGER(), nullable=False),
    sa.Column('parent_church_id_1', sa.INTEGER(), nullable=True),
    sa.Column('parent_church_id_2', sa.INTEGER(), nullable=True),
    sa.Column('seniority', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['human.church_id'], ),
    sa.ForeignKeyConstraint(['parent_church_id_1'], ['human.church_id'], ),
    sa.ForeignKeyConstraint(['parent_church_id_2'], ['human.church_id'], ),
    sa.PrimaryKeyConstraint('church_id'),
    sa.UniqueConstraint('church_id'),
    sa.UniqueConstraint('seniority')
    )
    op.create_table('lord',
    sa.Column('lord_id', sa.INTEGER(), nullable=False),
    sa.Column('church_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['human.church_id'], ),
    sa.PrimaryKeyConstraint('lord_id'),
    sa.UniqueConstraint('lord_id')
    )
    op.create_table('human',
    sa.Column('church_id', sa.INTEGER(), nullable=False),
    sa.Column('human_name', sa.VARCHAR(), nullable=True),
    sa.Column('sex', sa.VARCHAR(), nullable=True),
    sa.Column('birthday', sa.DATE(), nullable=True),
    sa.Column('capital', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('church_id')
    )
    op.create_table('occupation',
    sa.Column('profession', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('profession')
    )
    # ### end Alembic commands ###
